### ISSUE TITLE
[Bug]: App crash when user click on the "Book Ticket" Button on Event Details

### ISSUE THREAD

**Issue by maityamit** [DSC-PHCET/gdsc-android-app#46]
### Contact Details

maityamit308@gmail.com

#### then app crash
</br>

<img src="https://user-images.githubusercontent.com/74618071/159065019-08a99ca6-8a84-4b66-8c10-19c03db91bbc.jpg" width="30%" >

### Relevant log output

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.finite.gdscphcet, PID: 7332
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=null }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
        at android.app.Activity.startActivityForResult(Activity.java:5422)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:5380)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:5770)
        at android.app.Activity.startActivity(Activity.java:5723)
        at com.finite.gdscphcet.ui.EventDetailActivity.setUpcomingEventData$lambda-7$lambda-5(EventDetailActivity.kt:154)
        at com.finite.gdscphcet.ui.EventDetailActivity.$r8$lambda$HY_FhlAbEeT379NYNgSYxV5TIj4(Unknown Source:0)
        at com.finite.gdscphcet.ui.EventDetailActivity$$ExternalSyntheticLambda1.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7465)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7442)
        at android.view.View.access$3600(View.java:813)
        at android.view.View$PerformClick.run(View.java:28394)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7844)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SB2318** [comment]
Sorry, but it is working. Please update the repo and check again.

https://user-images.githubusercontent.com/87614560/159109234-551c3a53-9090-4a5d-86eb-e9a82a294e86.mp4

**Comment by maityamit** [comment]
@SB2318 ok
